### ISSUE TITLE
converging CNE doesn't seem good

### ISSUE THREAD

**Issue by lnyawen** [phyloacc/PhyloAcc#67]
Hello,

Thank you for making such great software. Recently I've been using Phyloacc to calculate the converged CNE. And I would like to ask you a few questions.

Firstly, after the calculation, I used logBF1(>10) and logBF2 (>1) to filter the converging CNEs. I noticed that I also need to use posterior_3 to filter it. I would like to know if that is the value found in *_rate_postZ_M2.txt's target_species__3 column.

Secondly, I am using the above three criteria to filter, and I find that I get very, very few results, the input has more than 700000 CNEs, and I only get a dozen or so results.

Thirdly, we plotted plot for these dozen results base the R script, and I found that the length of the branches of the target species doesn't seem to be the longest, not like the pattern of the results in the example data. The species marked in blue is my target species.
[157-st.tree.pdf](https://github.com/phyloacc/PhyloAcc/files/15141412/157-st.tree.pdf)

What do you think the problem might be?

Thanks
Yawen

**Comment by gwct** [comment]
Hi Yawen,
I think the column you are referring to is the posterior estimate of the conserved substitution rate for the M2 model. I'm not sure why you would want to filter your results based on that parameter since it doesn't tell you explicitly whether an element is conserved or accelerated. Maybe you could filter on the raw marginal likelihood, which would be in the elem_lik.txt file. But why do you think you need to do filtering in addition to the BFs? I'll note that there is also a third BF which compares M2 to M0. Is that what you wanted to filter on?

As for getting very few results, this will all depend on the cutoffs you choose for your BFs. You could try various cutoffs to see if you get different results, maybe first by lowering the BF1 cutoff.

For the target branches being too short, I'm not too sure why that would happen. Are you plotting the trees with branch lengths scaled by the rates estimated in M1? Otherwise, I'll ping @xyz111131 or @HanY-H to weigh in as they have more experience analyzing these results.

**Comment by lnyawen** [comment]
Hello,

Sorry for the late reply.

I mentioned using a third criterion, the value of some posterior probability, to filter the results because I saw that the article "Convergent regulatory evolution and loss of flight in paleognathous birds" mentions the value of the posterior probability in its Supplementary Materials, however, I'm not too sure which posterior probability it refers to, so I came to ask you about it. However, I'm not too sure which posteriori probability value is being referred to, so I'm asking for your advice. 

I'm looking for convergent CNEs, what other criteria do you think I should use for filtering besides the BF1 and BF2 values?

I'm using what should be the M2 rate to plot the branch lengths, using the script in the https://github.com/phyloacc/Hu-etal-2019-data/blob/main/R/plot.Rmd

**Comment by gwct** [comment]
Ah, I see. I misread which column you were using in the `*_rate_postZ_M2.txt` file. You are using "branch_name_3", not column 3. In that case I think you are correct. That would be the probability that that branch is in the accelerated state in model M2. I think that is a good thing to do, and is in line with what they did in the paper.

For the tree, if you are looking at M2, it is entirely possible that your target lineages won't stand out since M2 is the 'free' model -- any lineage can be in the accelerated state. If you want loci where only the target lineages can be in the accelerated state, you would want to use M1. In fact, using the BF1 and BF2 cutoffs are meant to tell you which loci fit best with M1 over the other two models, so I'm not quite clear on why you're using the M2 `_rate_postZ_` file or plotting the M2 rates.

**Comment by lnyawen** [comment]
Thanks for the answer, then I can use these three criterion to filter the results! 

I used M2 for my ploting because I used the script that exists here directly https://github.com/phyloacc/Hu-etal-2019-data/blob/2e4969bc2540713b605566a2fe5e2c2f8369bc3c/R/plot.Rmd#L39-L56. Would you mind taking a look at the script?

And I'll try to plot it with M1.

Thanks

**Comment by gwct** [comment]
I think that script is just an example and may not be tailored to your analysis. If you want to look at the results for M1 (where only your targets can be accelerated), then you should plot M1. If you want to see the full model, then you should plot M2, but it may not reflect the results you expect for the target lineages.

@xyz111131 could weigh in more with the specifics of that script.
